[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "charontak"
authors = [{ name = "Charontak contributors" }]
dynamic = [
  "version",
  "description",
  "readme",
  "requires-python",
  "license",
  "keywords",
  "classifiers",
  "dependencies",
]

[project.optional-dependencies]
with_takproto = ["pytak[with_takproto]"]
dev = ["pytest>=7.0", "pytest-asyncio>=0.23", "cryptography>=39.0.0"]

[project.scripts]
charontak = "charontak.cli:main"

[project.urls]
Homepage = "https://github.com/snstac/charontak"
Repository = "https://github.com/snstac/charontak"
Issues = "https://github.com/snstac/charontak/issues"
Documentation = "https://pytak.rtfd.io/"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
norecursedirs = [
  ".git",
  ".venv",
  "build",
  "deb_dist",
  "dist",
]
