---

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart COTBridge docker stack
  ansible.builtin.systemd_service:
    name: cotbridge-docker
    state: restarted
